### ISSUE TITLE
Add the forecast.sqlite file to the FG folder and link the alternative to the file

### ISSUE THREAD

**Issue by HenryGeorgist** [HydrologicEngineeringCenter/ForecastGenerator#5]
the forecast sqlite file will serve as the basis for the random forecast passed to the lifecycle directory. The root directory will keep a copy, and the plugin will create a modified version with each lifecycle. 
We need to be able to store a link to the alternative's original forecast with the plugin.

**Comment by HenryGeorgist** [comment]
@ktarbet can I get an example file with a fairly substantial amount of records for testing?

**Comment by ktarbet** [comment]
@HenryGeorgist   I've created a sample database with 106 locations --  106 time-series-of-ensembles.  The total number of ensembles is 127,561.

**Comment by HenryGeorgist** [comment]
Perfect. I will use that to start testing.

**Comment by HenryGeorgist** [comment]
I downloaded the file - I will set up my example WAT project to use it next week.

**Comment by HenryGeorgist** [comment]
Computing Forecast Generator Alternative: abcd
Simulation Time window is: 1 February 2020, 00:00; 1 July 2030, 24:00
Run Time window is: 6 February 2020, 14:00; 13 February 2020, 16:00
Event Time window is: 6 February 2020, 14:00; 13 February 2020, 16:00
Realization Number is: 0
Lifecycle Number is: 1
Event Number is: 1
Model Sequence number is: 0
Run Directory is: C:\Temp\wat\testing\runs\Without_Project_Conditions\test\realization 1\lifecycle 1\event 1\Forecast Generator\
DSS File Path is:C:\Temp\wat\testing\runs\Without_Project_Conditions\test\realization 1\lifecycle 1\simulation.dss
Input Data path is: C:\Temp\wat\testing\FG\TS_ensemble.db
